modLoader="javafml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/zbx1425/AEGuide/issues"
displayURL="https://github.com/zbx1425/AEGuide"
logoFile="logo.png"
authors="TeamAppliedEnergistics, Zbx1425"
license="See GitHub repository for details"

[[mods]]
modId="ae2"
version="0.0.0"
displayName="AEGuide"
description="The guide book from Applied Energistics 2."

[[dependencies.ae2]]
    modId="neoforge"
    type="REQUIRED"
    versionRange="${neoforge_version}"
    ordering="NONE"
    side="BOTH"

[[dependencies.ae2]]
    modId="minecraft"
    type="REQUIRED"
    versionRange="${minecraft_version}"
    ordering="NONE"
    side="BOTH"

# VanillaFix caused us grief in the past
# https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/8034
# https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/7539
[[dependencies.ae2]]
    modId="vanillafix"
    type="discouraged"
    reason="VanillaFix breaks some NeoForge features that AE2 depends on. Do not report AE2 bugs if VanillaFix is present."
